#!/usr/bin/env python3
"""Generate the benchmark's fixture corpus — synthetically, and locally.

Run this only to (re)build `tests/fixtures/audio/`. `make bench` does **not**
run it: the WAVs are committed, so the benchmark replays the same bytes on
every machine and on CI, where no TTS may exist.

    python3 scripts/make_fixtures.py

Why synthesised rather than recorded:

* **Licence.** Third-party speech corpora carry terms this repository cannot
  accept on a user's behalf, and scraped audio carries worse. Machine-generated
  speech from the operating system's own voice has no such encumbrance.
* **Privacy.** The obvious alternative — real caller audio — is exactly what a
  public repository must never contain, whatever the consent story.

The corpus is deliberately tiny. It demonstrates the measurement; it is not a
dataset, and no vendor ranking derived from six utterances should be believed.

The transcript written alongside each clip is the text handed to the
synthesiser, so it is a genuine reference rather than an assumed one. That is
what makes the WER column legitimate here — see `voicerouter/bench.py`.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CORPUS = ROOT / "tests" / "fixtures" / "audio"

#: Short banking-domain utterances, matching what this pattern's agent handles.
#: A couple are deliberately awkward — digits and an alphanumeric reference —
#: because that is where vendors actually diverge, and a corpus of easy
#: sentences would show a flattering agreement that means nothing.
UTTERANCES: list[tuple[str, str]] = [
    ("balance", "What is the balance on my current account?"),
    ("transfer", "I would like to transfer two hundred and fifty pounds to my savings."),
    ("digits", "My account number is four eight one six two zero."),
    ("reference", "The payment reference is alpha seven delta nine."),
    ("cancel", "Cancel that, I want to speak to a human."),
    ("confirm", "Yes, that is correct."),
]

#: 16 kHz mono PCM16: what every local ASR here wants, and what `to_rasa_audio`
#: converts from. Telephony is 8 kHz, but downsampling is lossy and one-way, so
#: the corpus is stored at the higher rate and narrowed on demand.
SAMPLE_RATE = 16000


def _require(tool: str) -> str:
    path = shutil.which(tool)
    if not path:
        sys.exit(
            f"{tool} not found. This generator uses the host's own TTS and is "
            f"macOS-only by design; the corpus it produces is committed, so "
            f"running the benchmark needs neither."
        )
    return path


def main() -> int:
    say, ffmpeg = _require("say"), _require("ffmpeg")
    CORPUS.mkdir(parents=True, exist_ok=True)

    manifest = []
    for name, text in UTTERANCES:
        aiff = CORPUS / f"{name}.aiff"
        wav = CORPUS / f"{name}.wav"
        # A single fixed voice: varying it would vary the difficulty, and the
        # benchmark is measuring vendors against each other, not against voices.
        subprocess.run([say, "-v", "Daniel", "-o", str(aiff), text], check=True)
        subprocess.run(
            [ffmpeg, "-y", "-loglevel", "error", "-i", str(aiff),
             "-ac", "1", "-ar", str(SAMPLE_RATE), "-acodec", "pcm_s16le", str(wav)],
            check=True,
        )
        aiff.unlink()
        manifest.append({"name": name, "audio": wav.name, "reference": text})
        print(f"  {wav.name:<16} {wav.stat().st_size:>7} bytes  {text}")

    (CORPUS / "manifest.json").write_text(
        json.dumps(
            {
                "description": (
                    "Synthetic speech generated by scripts/make_fixtures.py using "
                    "the host operating system's built-in TTS. No third-party "
                    "audio and no recorded caller audio. Safe to redistribute."
                ),
                "sample_rate": SAMPLE_RATE,
                "utterances": manifest,
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )
    print(f"\nWrote {len(manifest)} fixtures to {CORPUS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
